config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :leave_requests do
    collection do
      get :new
      get  :search_leave
      get  :delete_leave
      post  :delete_leave
      post :search_leave
      delete :leave_delete
      end
  end

  match '*path' => redirect('/'), via: [:get, :post, :put, :patch, :delete, :options, :head]
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :pto_requests
end

app/models/pto_request.rb
class PtoRequest < ActiveRecord::Base
  belongs_to :employee
  attr_accessor :from_date,:to_date,:emp_name,:emp_id,:pto_dt
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:emp_no, :emp_name, :emp_email)
    end
end

app/controllers/leave_requests_controller.rb
class LeaveRequestsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def new
  @pto = PtoRequest.new
  @emp_name = Employee.all.pluck(:emp_name,:emp_no)
    # p @emp_name
  end

  def create
    @pto_dates = PtoRequest.new(pto_date_params)
    from_date=Date.strptime(params[:pto_request][:from_date], '%d/%m/%Y')
    to_date=Date.strptime(params[:pto_request][:to_date], '%d/%m/%Y')
    tot_dates = (from_date..to_date).to_a.map{|x| DateTime.parse(x.to_s).strftime("%d/%m/%Y")}
    from_duration = params[:pto_request][:from_duration]
    to_duration = params[:pto_request][:to_duration]
    emp_name =  Employee.where(:emp_no => params[:pto_request][:emp_no]).pluck(:emp_name).first

    if(from_date == to_date)
      if(params[:pto_request][:from_duration] =="Session 1")
        duration = "1st Half"
      elsif(params[:pto_request][:from_duration] =="Full Day")
        duration = "Full Day";
      else
        duration = "2nd Half";
      end
      PtoRequest.create(:pto_date=>tot_dates.first,:emp_no=>params[:pto_request][:emp_no],:Emp_Name=>emp_name,:leave_type=>params[:pto_request][:leave_type],:leave_duration=>duration)
    else
    if(from_duration =="Session 1" && to_duration =="Session 1" )
      tot_dates.each { |x|
        if(tot_dates.last == x)
          PtoRequest.create(:pto_date=>x,:emp_no=>params[:pto_request][:emp_no],:Emp_Name=>emp_name,:leave_type=>params[:pto_request][:leave_type],:leave_duration=>"1st Half")
        else
          PtoRequest.create(:pto_date=>x,:emp_no=>params[:pto_request][:emp_no],:Emp_Name=>emp_name,:leave_type=>params[:pto_request][:leave_type],:leave_duration=>"Full")
        end
      }
    end
    if(from_duration =="Session 1" && to_duration =="Session 2" )
      tot_dates.each { |x|
        if(tot_dates.last == x)
          PtoRequest.create(:pto_date=>x,:emp_no=>params[:pto_request][:emp_no],:Emp_Name=>emp_name,:leave_type=>params[:pto_request][:leave_type],:leave_duration=>"Full")
        else
          PtoRequest.create(:pto_date=>x,:emp_no=>params[:pto_request][:emp_no],:Emp_Name=>emp_name,:leave_type=>params[:pto_request][:leave_type],:leave_duration=>"Full")
        end
      }
    end
    if(from_duration =="Session 2" && to_duration =="Session 1" )
      tot_dates.each { |x|
        if(tot_dates.last == x)
          PtoRequest.create(:pto_date=>x,:emp_no=>params[:pto_request][:emp_no],:Emp_Name=>emp_name,:leave_type=>params[:pto_request][:leave_type],:leave_duration=>"1st Half")
        else
          PtoRequest.create(:pto_date=>x,:emp_no=>params[:pto_request][:emp_no],:Emp_Name=>emp_name,:leave_type=>params[:pto_request][:leave_type],:leave_duration=>"2nd Half")
        end
      }
    end
    if(from_duration =="Session 2" && to_duration =="Session 2" )
      tot_dates.each { |x|
        if(tot_dates.last == x)
          PtoRequest.create(:pto_date=>x,:emp_no=>params[:pto_request][:emp_no],:Emp_Name=>emp_name,:leave_type=>params[:pto_request][:leave_type],:leave_duration=>"Full")
        else
          PtoRequest.create(:pto_date=>x,:emp_no=>params[:pto_request][:emp_no],:Emp_Name=>emp_name,:leave_type=>params[:pto_request][:leave_type],:leave_duration=>"2nd Half")
        end
      }
    end
    end
      render "view"
  end

  def show
   @pto_date = PtoRequest.all
  end

  def search_leave
    @pto ="";
    if ( params[:emp_name] == nil && params[:emp_id] == nil && params[:pto_dt] == nil)
      @emp_name =  PtoRequest.all.distinct.pluck(:Emp_Name)
      @pto_date = PtoRequest.all.order(pto_date: :desc)
    else
      @emp_name =  PtoRequest.all.distinct.pluck(:Emp_Name)
      p = {
          :Emp_Name => params[:emp_name],
          :emp_no => params[:emp_id],
          :pto_date => params[:pto_dt],
      }
      p.reject!{|b,a| a.nil? or a.eql?"" }
      @pto_date = PtoRequest.where(p).order(pto_date: :desc)
    end
  end

  def delete_leave
    @pto ="";
    if ( params[:emp_name] == nil && params[:emp_id] == nil && params[:pto_dt] == nil)
      @emp_name =  PtoRequest.all.distinct.pluck(:Emp_Name)
      @pto_date = PtoRequest.all
    else
      @emp_name =  PtoRequest.all.distinct.pluck(:Emp_Name)
      p = {
          :Emp_Name => params[:emp_name],
          :emp_no => params[:emp_id],
          :pto_date => params[:pto_dt],
      }
      p.reject!{|b,a| a.nil? or a.eql?"" }
      @pto_date = PtoRequest.where(p)
    end
  end

  def leave_delete
    @leave = PtoRequest.where(:id=>params[:leave_id]).first.delete
    respond_to do |format|
      format.js {render js: "window.location = '#{delete_leave_leave_requests_path}';", notice: 'Leave was successfully deleted.'}
    end
  end

  def pto_date_params
    params.require(:pto_request).permit(:emp_no, :from_date,:to_date,:leave_type,:Leave_duration)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/pto_requests_helper.rb
module PtoRequestsHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :emp_no %><br>
    <%= f.text_field :emp_no %>
  </div>
  <div class="field">
    <%= f.label :emp_name %><br>
    <%= f.text_field :emp_name %>
  </div>
  <div class="field">
    <%= f.label :emp_email %><br>
    <%= f.text_field :emp_email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table class="table" style="width: 50%;">
  <thead>
    <tr>
      <th>Emp no</th>
      <th>Emp name</th>
      <th>Emp email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.emp_no %></td>
        <td><%= employee.emp_name %></td>
        <td><%= employee.emp_email %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Employee', new_employee_path %>

<%= link_to 'New Leave Requests', new_leave_request_path %>

<%= link_to 'View Leave Requests', delete_leave_leave_requests_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emp no:</strong>
  <%= @employee.emp_no %>
</p>

<p>
  <strong>Emp name:</strong>
  <%= @employee.emp_name %>
</p>

<p>
  <strong>Emp email:</strong>
  <%= @employee.emp_email %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pto</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/leave_requests/delete_leave.html.erb
<p id="notice"><%= notice %></p>
<%= form_for(@pto) do |f| %>
    <table class="table" style="width: 73%;">
      <tr>
        <td>Employee Name</td>
        <td>  <%= select_tag  "emp_name", options_for_select(@emp_name), :prompt => "Select Employee" %></td>
        <td>Employee Id</td>
        <td> <%= f.text_field :emp_id ,{:id=>'txtEmpId'} %></td>
        <td>Leave Date</td>
        <td> <%= f.text_field :pto_dt ,{:id=>'txtPtoDate'} %></td>
        <td><%= f.submit 'Search' %></td>
      </tr>
    </table>
<% end %>
<table class="table"  style="width: 73%;">

  <tr>
    <th>Employee Name</th>
    <th>Employee Code</th>
    <th>Leave Date</th>
    <th>Leave Type</th>
    <th>Leave Duration</th>
    <th>Delete</th>
  </tr>
  <% @pto_date.each do |pto| %>
      <tr>
        <td>
          <%= pto.Emp_Name %>
        </td>
        <td>
          <%= pto.emp_no %>
        </td>
        <td>
          <%= pto.pto_date %>
        </td>
        <td>
          <%= pto.leave_type %>
        </td>
        <td>
          <%= pto.leave_duration %>
        </td>
        <td>
          <a href="javascript:void(0);" onclick="javascript:Delete_Leave('<%= pto.id %>');">Delete</a>
        </td>
      </tr>
  <% end -%>
</table>
<script>
    $(document).ready(function(){
        $("#txtPtoDate").datepicker({
            dateFormat: 'yy-mm-dd',
            numberOfMonths: 1
        });
    });
    function Delete_Leave(leave_id)
    {
        var txt;
        var r = confirm("Do you want to delete");
        if (r == true) {
            $.ajax({
                type: "DELETE",
                url: "<%= leave_delete_leave_requests_path %>",
                data: { 'leave_id': leave_id },
                success: function (data) {
                }
            });
        }
    }
</script>

app/views/leave_requests/index.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">

<%= form_for(@pto) do |f| %>
<table>
  <tr>
    <td>Employee Name</td>
    <td><select id="" name=""></select> </td>
  </tr>
  <tr>
    <td>PTO Date</td>
    <td>

    </td>
    <!--<td> <input type="text" id="datepicker"></td>-->
  </tr>
  <tr>
    <td><button>Save</button></td>
    <td><button>Cancel</button></td>
  </tr>
</table>
<% end %>
<script>
    $(function() {
        $( "#datepicker" ).datepicker();
    });
</script>

app/views/leave_requests/leave_delete.html.erb
<b>Deleted Successfully</b>
<div>

  <%= link_to 'New Leave Requests', new_leave_request_path %>

  <%= link_to 'View Leave Requests', search_leave_leave_requests_path %>

</div>

app/views/leave_requests/new.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<%= form_for @pto, :url => leave_requests_path, :html => { :id => "new_leave" }  do |f| %>
    <table class="table" style="width: 50%;">
      <tr>
        <td>Employee Name</td>
        <td>
          <div class="col-sm-12"> <%= select_tag   "pto_request[emp_no]", options_for_select(@emp_name), :prompt => "Select Employee",:style=>"width:173px;" ,:class=>"form-control" %></div>
        </td>

      </tr>
      <tr>
        <td>
          Leave Type
        </td>
        <td>
          <div class="col-sm-12"><%= select_tag  "pto_request[leave_type]", options_for_select(["Work From Home","Casual Leave","Privilege Leave","LOP"]), :prompt => "Select Leave Type",:style=>"width:173px;" ,:class=>"form-control" %></div>
        </td>
      </tr>
      <tr>
        <td>
          From Date
        </td>
        <td>
          <div class="col-sm-5"> <%= f.text_field :from_date ,{:id=>'txtFromDate',:class=>"form-control",:style=>"width: 173px;"}%></div>
          <div class="col-sm-5"><%= select_tag  "pto_request[from_duration]", options_for_select(["Session 1","Session 2"]), :prompt => "Select Session",:id=>"ddlFromDate" ,:style=>"width:173px;",:class=>"form-control" %></div>
        </td>
      </tr>
      <tr>
        <td>To Date</td>
        <td>
          <div class="col-sm-5"><%= f.text_field :to_date ,{:id=>'txtToDate',:class=>"form-control",:style=>"width: 173px;"} %></div>
            <div class="col-sm-5"><%= select_tag  "pto_request[to_duration]", options_for_select(["Session 1","Session 2"]), :prompt => "Select Session",:id=>"ddlToDate" ,:style=>"width:173px;",:class=>"form-control" %></div>
        </td>
      </tr>
      <tr>
        <td></td>
        <td>
          <%= f.submit 'Save' ,id: 'btnSave', class: 'btn btn-sm btn-primary' %>
          <%= link_to 'Cancel', delete_leave_leave_requests_path, class: 'btn btn-sm btn-primary' %></td>
      </tr>
    </table>
<% end %>
<script>
    $(document).ready(function(){
        $("#txtFromDate").datepicker({
        dateFormat: 'dd/mm/yy',
            numberOfMonths: 1,
            onSelect: function(selected) {
                $("#txtToDate").datepicker("option","minDate", selected);
                if($("#txtFromDate").val() == $("#txtToDate").val())
                {
                    $("#ddlToDate").hide();
                    $("#ddlFromDate option[value='Full Day']").remove();
                    $('#ddlFromDate').append( new Option("Full Day","Full Day") );
                }
                else
                {
                    $("#ddlFromDate option[value='Full Day']").remove();
                    $("#ddlToDate").show();
                }

            }
        });
        $("#txtToDate").datepicker({
            dateFormat: 'dd/mm/yy',
            numberOfMonths: 1,
            onSelect: function(selected) {
                $("#txtFromDate").datepicker("option","maxDate", selected);
                if($("#txtFromDate").val() == $("#txtToDate").val())
                {
                $("#ddlToDate").hide();
                $("#ddlFromDate option[value='Full Day']").remove();
                $('#ddlFromDate').append( new Option("Full Day","Full Day") );
                }
                else
                {
                    $("#ddlFromDate option[value='Full Day']").remove();
                    $("#ddlToDate").show();
                }

            }
        });
        $( "#btnSave" ).click(function() {
            var emp_name  = $("#pto_request_emp_no option:selected").text();
            var leave_type  = $("#pto_request_leave_type option:selected").text();
            var from_date =$( "#txtFromDate").val();
            var to_date =$( "#txtToDate").val();
            if(emp_name=="Select Employee")
            {
                alert('Please Select Employee Name');
                return false;
            }
            else if(leave_type=="Select Leave Type")
            {
                alert('Please Select Leave Type');
                return false;
            }
            else
            {
                $("#new_leave").submit();
            }
        });


    });



</script>

app/views/leave_requests/search_leave.html.erb
<%= form_for(@pto) do |f| %>
<table class="table"  style="width: 73%;">
  <tr>
    <td>Employee Name</td>
    <td>  <%= select_tag  "emp_name", options_for_select(@emp_name), :prompt => "Select Employee" %></td>
    <td>Employee Id</td>
    <td> <%= f.text_field :emp_id ,{:id=>'txtEmpId'} %></td>
    <td>Leave Date</td>
    <td> <%= f.text_field :pto_dt ,{:id=>'txtPtoDate'} %></td>
    <td><%= f.submit 'Search' %></td>
  </tr>
</table>
<% end %>
<table class="table"  style="width: 73%;">
  <tr>
    <th>Employee Name</th>
    <th>Employee Code</th>
    <th>Leave Date</th>
    <th>Leave Type</th>
    <th>Leave Duration</th>
  </tr>
  <% @pto_date.each do |pto| %>
      <tr>
        <td>
          <%= pto.Emp_Name %>
        </td>
        <td>
          <%= pto.emp_no %>
        </td>
        <td>
          <%= pto.pto_date %>
        </td>
        <td>
          <%= pto.leave_type %>
        </td>
        <td>
          <%= pto.leave_duration %>
        </td>
      </tr>
  <% end -%>
</table>
<script>
    $(document).ready(function(){
        $("#txtPtoDate").datepicker({
            dateFormat: 'yy-mm-dd',
            numberOfMonths: 1
        });
    });
</script>

app/views/leave_requests/show.html.erb
<table style="border: 1px solid">


<tr style="background: #CCCCCC;">
    <th>Employee Code</th>
  <th>Pto Date</th>
  <th>Leave Duration</th>
</tr>
<% @pto_date.each do |pto| -%>
    <tr>
        <td>
          <%= pto.emp_no %>
        </td>
        <td>
          <%= pto.pto_date %>
        </td>
      <td>
        <%= pto.leave_duration %>
      </td>
    </tr>
<% end -%>
</table>

app/views/leave_requests/view.html.erb
<b>Saved Successfully</b>
<div>

<%= link_to 'New Leave Requests', new_leave_request_path %>

<%= link_to 'View Leave Requests', search_leave_leave_requests_path %>

</div>

app/views/pto_requests/index.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">

<%= form_for(@pto) do |f| %>
<table>
  <tr>
    <td>Employee Name</td>
    <td><select id="" name=""></select> </td>
  </tr>
  <tr>
    <td>PTO Date</td>
    <td>

    </td>
    <!--<td> <input type="text" id="datepicker"></td>-->
  </tr>
  <tr>
    <td><button>Save</button></td>
    <td><button>Cancel</button></td>
  </tr>
</table>
<% end %>
<script>
    $(function() {
        $( "#datepicker" ).datepicker();
    });
</script>

app/views/pto_requests/new.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">

<%#= form_for(@pto) do |f| %>
    <table style="border: 1px solid;">
      <tr>
        <td>Employee Name</td>
        <td>
          <%= select_tag  "pto_request[emp_no]", options_for_select(@emp_name), :prompt => "Select Employee" %>
        </td>
      </tr>
      <tr>
        <td>PTO Date</td>
        <td>
          <%= f.text_field :from_date ,{:id=>'txtFromDate'} %>
          <%= f.text_field :to_date ,{:id=>'txtToDate'} %>
        </td>
      </tr>
      <tr>
        <td></td>
        <td><%= f.submit 'Save' %> <button>Cancel</button></td>
      </tr>
    </table>
<%# end %>
<script>
    $(document).ready(function(){
        $("#txtFromDate").datepicker({
        dateFormat: 'dd/mm/yy',
            numberOfMonths: 1,
            onSelect: function(selected) {
                $("#txtToDate").datepicker("option","minDate", selected)
            }
        });
        $("#txtToDate").datepicker({
            dateFormat: 'dd/mm/yy',
            numberOfMonths: 1,
            onSelect: function(selected) {
                $("#txtFromDate").datepicker("option","maxDate", selected)
            }
        });
    });
</script>

app/views/pto_requests/search_pto.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">
<%= form_for(@pto) do |f| %>
<table>
  <tr>
    <td>Employee Name</td>
    <td>  <%= select_tag  "emp_name", options_for_select(@emp_name), :prompt => "Select Employee" %></td>
    <td>Employee Id</td>
    <td> <%= f.text_field :emp_id ,{:id=>'txtEmpId'} %></td>
    <td>PTO Date</td>
    <td> <%= f.text_field :pto_dt ,{:id=>'txtPtoDate'} %></td>
    <td><%= f.submit 'Search' %></td>
  </tr>
</table>
<% end %>
<table style="border: 1px solid">

  <tr style="background: #CCCCCC;">
    <th>Employee Name</th>
    <th>Employee Code</th>
    <th>Pto Date</th>
  </tr>
  <% @pto_date.each do |pto| %>
      <tr>
        <td>
          <%= pto.Emp_Name %>
        </td>
        <td>
          <%= pto.emp_no %>
        </td>
        <td>
          <%= pto.pto_date %>
        </td>
      </tr>
  <% end -%>
</table>

<script>
    $(document).ready(function(){
        $("#txtPtoDate").datepicker({
            dateFormat: 'yy-mm-dd',
            numberOfMonths: 1
        });
    });
</script>

app/views/pto_requests/show.html.erb
<table style="border: 1px solid">


<tr style="background: #CCCCCC;">
    <th>Employee Code</th>
  <th>Pto Date</th>
</tr>
<% @pto_date.each do |pto| -%>
    <tr>
        <td>
          <%= pto.emp_no %>
        </td>
        <td>
          <%= pto.pto_date %>
        </td>
    </tr>
<% end -%>
</table>